Settings:
  Plugin:
    debug: true
  Gui:
    open: false
    title: "&b&lT&a&lw&6&li&3&ls&d&lt&e&le&c&lr"
    size: 1
    SizeSelector:
      items:
        type: BLUE_STAINED_GLASS_PANE
        show-amounts: true
  Hook:
    WorldGuard:
      enabled: true
      take-players-inventory: true
      game-region: "twister"

  Game:
    take-players-inv-on-join: true
    subtracted-time-multiplier: 0.8
    seconds-duration-round: 8
    min-players: 2
    max-field-size: 9

Arena:
  world: "Your world name"
  pos1:
    x:
    y: -58
    z:
  pos2:
    x:
    y: -58
    z:
  teleport-position:
    x:
    y:
    z:
  lose-position:
    x:
    y:
    z: