Settings:
  Gui:
    open: false
    materials:
      random: true
      custom: FEATHER
  Game:
    subtracted-time-multiplier: 0.8 #Double
    seconds-duration-round: 160 #8 seconds
    max-players: 40
    min-players: 2
    max-field-size: 10
    time-to-player-out: 40 #ticks = 2 seconds

Arena:
  world: "Your world name"
  pos1:
    x:
    y: -58
    z:
  pos2:
    x:
    y: -58
    z:
  teleport-position:
    x:
    y:
    z:
  lose-position:
    x:
    y:
    z: